replicaCount: 2

image:
  repository: your-registry/go-ws-gateway-proxy
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # ─── single source of truth for your public host ───
  # used in the IngressRoute Host(...) match and TLS hosts
  host: ws-public-host-name.example.com
  # ─── single source of truth for CORS/allowed origins ───
  # used in the CORS middleware
  allowedOrigins: '*.example.com'
  tls:
    secretName: tls-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: # Projected into ConfigMap
  WS_ALLOWED_ORIGINS: '*.example.com'
  JWT_COOKIE_NAME: 'session'
  GRACEFUL_DRAIN_TIMEOUT_SECONDS: '30'
  WS_IDLE_TIMEOUT_SECONDS: '60'
  WS_WRITE_TIMEOUT_SECONDS: '10'
  JWKS_URL: 'https://keycloak.example.com/realms/myrealm/protocol/openid-connect/certs'
  JWKS_TTL_MINUTES: '10'

secrets: # Projected into Kubernetes Secret
  JWT_EXPECTED_ISSUER: ''
  JWT_EXPECTED_AUDIENCE: ''
  JWT_VALID_ALGORITHMS: 'RS256'
  REDIS_URL: ''
  POSTGRES_DSN: ''
  UPSTREAM_WS_URL: 'ws://rabbitmq:15675/ws'
