apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-ws-gateway-proxy.fullname" . }}-secrets
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
