apiVersion: v1
kind: ConfigMap
metadata:
  name: go-ws-gateway-proxy-config
data:
  INGRESS_HOST: ws-public-host-name.example.com
  WS_ALLOWED_ORIGINS: "*.example.com"
  JWT_COOKIE_NAME: "session"
  GRACEFUL_DRAIN_TIMEOUT_SECONDS: "30"
  WS_IDLE_TIMEOUT_SECONDS: "90"
  WS_WRITE_TIMEOUT_SECONDS: "10"
  WS_CONTROL_TIMEOUT_SECONDS: "1"
  CB_FAILURE_THRESHOLD: "5"
  CB_OPEN_TIMEOUT_SECONDS: "60"
  CB_HEALTHCHECK_INTERVAL_SECONDS: "30"
  WS_DIAL_RETRY_MAX: "3"
  WS_DIAL_RETRY_INTERVAL_SECONDS: "2"
  RATE_LIMIT_PER_SECOND: "10"
  RATE_LIMIT_BURST: "30"
  JWKS_URL: https://keycloak.example.com/realms/myrealm/protocol/openid-connect/certs
  JWKS_TTL_MINUTES: "10"
  JWT_CACHE_STORE: "redis"
  JWT_CACHE_PREFIX: "jwt_cached_token_"
