apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: go-ws-gateway-proxy-config
    literals:
      # single source of truth for your ingress host and CORS origins:
      - INGRESS_HOST=ws-public-host-name.example.com
      - WS_ALLOWED_ORIGINS=*.example.com # comma separated single string, replace with your allowed origins

vars:
  - name: INGRESS_HOST
    objref:
      kind: ConfigMap
      name: go-ws-gateway-proxy-config
      apiVersion: v1
    fieldref:
      fieldpath: data.INGRESS_HOST
  - name: WS_ALLOWED_ORIGINS
    objref:
      kind: ConfigMap
      name: go-ws-gateway-proxy-config
      apiVersion: v1
    fieldref:
      fieldpath: data.WS_ALLOWED_ORIGINS

commonLabels:
  app: go-ws-gateway-proxy

generatorOptions:
  disableNameSuffixHash: true
