apiVersion: v1
kind: Secret
metadata:
  name: go-ws-gateway-proxy-secrets
type: Opaque
stringData:
  # these should be overridden in overlays
  JWT_EXPECTED_ISSUER: ''
  JWT_EXPECTED_AUDIENCE: '' # comma separated single string
  JWT_VALID_ALGORITHMS: 'RS256' # comma separated single string
  # optional external cache
  REDIS_URL: ''
  POSTGRES_DSN: ''
  UPSTREAM_WS_URL: 'ws://rabbitmq:15675/ws'
